//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employee_API.Models
{
    using FluentValidation;
    using FluentValidation.Attributes;
    using System;
    using System.Collections.Generic;
    
    [Validator(typeof(EmployeeValidator))]
    public partial class Employee
    {
        public int EmployeeID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmpCode { get; set; }
        public string Position { get; set; }
        public string Office { get; set; }
    }

    public class EmployeeValidator : AbstractValidator<Employee>
    {
        public EmployeeValidator()
        {
            RuleFor(x => x.FirstName).NotEmpty().WithMessage("The FirstName cannot be blank")
                .Length(0, 100).WithMessage("First name cannot be more than 20 characters");

            RuleFor(x => x.LastName).NotEmpty().WithMessage("The LastName cannot be blank");
        }
    }
}
